export const remainingPlacesArray = {
  "Bhojpur": [
    { name: "Aranya Devi Temple", category: "Religious" },
    { name: "Veer Kunwar Singh Fort", category: "Historical" },
    { name: "Sun Temple Dev", category: "Religious" },
    { name: "Masadh", category: "Historical" },
    { name: "Jain Bala Vishram", category: "Religious" },
    { name: "Bakhari", category: "Historical" },
    { name: "Lakes of Ara", category: "Rivers / Lakes / Ghats" },
    { name: "Sinha Ghat", category: "Rivers / Lakes / Ghats" },
    { name: "Jagdishpur Fair", category: "Cultural / Art villages" },
    { name: "Maharaja College Historical Building", category: "Museum / Cultural" }
  ],
  "Buxar": [
    { name: "Buxar Fort", category: "Historical" },
    { name: "Ramrekha Ghat", category: "Rivers / Lakes / Ghats" },
    { name: "Sita Ram Upadhyay Museum", category: "Museum / Cultural" },
    { name: "Chausa Hoard Site", category: "Historical" },
    { name: "Kathkauli Maidan", category: "Historical" },
    { name: "Navlakha Mandir", category: "Religious" },
    { name: "Brahmeshwar Nath Temple", category: "Religious" },
    { name: "Gauri Shankar Temple", category: "Religious" },
    { name: "Bhojpur Kadim", category: "Historical" },
    { name: "Chausa Battlefield", category: "Historical" }
  ],
  "Siwan": [
    { name: "Ziradei", category: "Historical" },
    { name: "Mehasan", category: "Religious" },
    { name: "Don", category: "Historical" },
    { name: "Faridpur", category: "Cultural / Art villages" },
    { name: "Koron Dih", category: "Historical" },
    { name: "Panchmukhi Shiv Mandir", category: "Religious" },
    { name: "Burhiya Mai Mandir", category: "Religious" },
    { name: "Amarnath Temple Siwan", category: "Religious" },
    { name: "Raghunathpur Ghat", category: "Rivers / Lakes / Ghats" },
    { name: "Mahendra Nath Temple", category: "Religious" }
  ],
  "Gopalganj": [
    { name: "Thawe Mandir", category: "Religious" },
    { name: "Dighwa Dubauli", category: "Historical" },
    { name: "Husepur", category: "Historical" },
    { name: "Lakri Dargah", category: "Religious" },
    { name: "Gopalganj Museum", category: "Museum / Cultural" },
    { name: "Shire-e-Tariqat Dargah", category: "Religious" },
    { name: "Kali Ashtan", category: "Religious" },
    { name: "Kakrighat", category: "Rivers / Lakes / Ghats" },
    { name: "Bangali Babu Ka Pokhara", category: "Rivers / Lakes / Ghats" },
    { name: "Gandak Barrage Gopalganj", category: "Scenic / Viewpoints" }
  ],
  "Sitamarhi": [
    { name: "Punaura Dham", category: "Religious" },
    { name: "Janaki Temple", category: "Religious" },
    { name: "Haleshwar Sthan", category: "Religious" },
    { name: "Panth Pakar", category: "Religious" },
    { name: "Bodhayan Sarovar", category: "Rivers / Lakes / Ghats" },
    { name: "Shukeshwar Sthan", category: "Religious" },
    { name: "Baghi Math", category: "Museum / Cultural" },
    { name: "Sitamarhi Museum", category: "Museum / Cultural" },
    { name: "Goroul Sharif", category: "Religious" },
    { name: "Deokuli Dham", category: "Religious" }
  ],
  "Sheohar": [
    { name: "Bhaoprasad Singh Fort", category: "Historical" },
    { name: "Matsyagandha Lake", category: "Rivers / Lakes / Ghats" },
    { name: "Tariyani Chhapra", category: "Religious" },
    { name: "Bari Sangat Temple", category: "Religious" },
    { name: "Dak Bungalow Sheohar", category: "Historical" },
    { name: "Ghoghikund", category: "Rivers / Lakes / Ghats" },
    { name: "Bagmati River Front", category: "Rivers / Lakes / Ghats" },
    { name: "Sheohar Estate Ruins", category: "Historical" },
    { name: "Mahadev Kothi", category: "Religious" },
    { name: "Deokuli Temple Sheohar", category: "Religious" }
  ],
  "Madhubani": [
    { name: "Saurath Sabha", category: "Museum / Cultural" },
    { name: "Kapileshwar Sthan", category: "Religious" },
    { name: "Uchaith Bhavani", category: "Religious" },
    { name: "Bhawanipur", category: "Historical" },
    { name: "Rajnagar Palace Ruins", category: "Historical" },
    { name: "Jhanjharpur Market", category: "Cultural / Art villages" },
    { name: "Navlakha Palace Madhubani", category: "Historical" },
    { name: "Kakolat Waterfall Madhubani", category: "Rivers / Lakes / Ghats" },
    { name: "Eksari", category: "Religious" },
    { name: "Mangalgarh", category: "Historical" }
  ],
  "Samastipur": [
    { name: "Vidyapati Dham", category: "Religious" },
    { name: "Thaneshwar Temple", category: "Religious" },
    { name: "Khudneshwar Asthan", category: "Religious" },
    { name: "Kariyan", category: "Historical" },
    { name: "Mangalgarh Samastipur", category: "Historical" },
    { name: "Khatu Shyam Temple", category: "Religious" },
    { name: "Mahnar Ghat", category: "Rivers / Lakes / Ghats" },
    { name: "Shri Ram Temple Samastipur", category: "Religious" },
    { name: "Morwa", category: "Cultural / Art villages" },
    { name: "Dalsinghsarai", category: "Historical" }
  ],
  "Saharsa": [
    { name: "Tara Sthan", category: "Religious" },
    { name: "Sun Temple Saharsa", category: "Religious" },
    { name: "Kandaha Sun Temple", category: "Historical" },
    { name: "Banma Itahri", category: "Historical" },
    { name: "Matsyagandha Madhopur", category: "Rivers / Lakes / Ghats" },
    { name: "Mahishi", category: "Historical" },
    { name: "Durga Mandir Saharsa", category: "Religious" },
    { name: "Laxminath Gosain Asthan", category: "Religious" },
    { name: "Udakishunganj", category: "Historical" },
    { name: "Dharamshala Ghat", category: "Rivers / Lakes / Ghats" }
  ],
  "Supaul": [
    { name: "Koshi Barrage", category: "Rivers / Lakes / Ghats" },
    { name: "Veena Dham", category: "Religious" },
    { name: "Kapooreshwar Mahadev", category: "Religious" },
    { name: "Gandhi Maidan Supaul", category: "Parks / Gardens" },
    { name: "Triveniganj", category: "Historical" },
    { name: "Nirmali", category: "Cultural / Art villages" },
    { name: "Koshi Bird Sanctuary", category: "Wildlife / Nature" },
    { name: "Pipra C.H.C Campus", category: "Historical" },
    { name: "Chattapur", category: "Religious" },
    { name: "Hardiya", category: "Historical" }
  ],
  "Madhepura": [
    { name: "Singheshwar Asthan", category: "Religious" },
    { name: "B.P. Mandal Memorial", category: "Museum / Cultural" },
    { name: "Dakini Sthan", category: "Religious" },
    { name: "Srinagar Madhepura", category: "Historical" },
    { name: "Chusa", category: "Cultural / Art villages" },
    { name: "Murho", category: "Cultural / Art villages" },
    { name: "Triveniganj Fort", category: "Historical" },
    { name: "Kariyan Madhepura", category: "Rivers / Lakes / Ghats" },
    { name: "Mahadev Mandir", category: "Religious" },
    { name: "Gandhi Maidan Madhepura", category: "Parks / Gardens" }
  ],
  "Purnia": [
    { name: "Puran Devi Temple", category: "Religious" },
    { name: "Jalalgarh Fort", category: "Historical" },
    { name: "Kamakya Mandir", category: "Religious" },
    { name: "Dargah of Hazrat Mustafa Jamalul Haq", category: "Religious" },
    { name: "Forbesganj Market", category: "Cultural / Art villages" },
    { name: "Bhavanipur", category: "Historical" },
    { name: "Dharhara", category: "Rivers / Lakes / Ghats" },
    { name: "Line Bazaar", category: "Cultural / Art villages" },
    { name: "Khajanchi Haat", category: "Historical" },
    { name: "Kosi River Bank", category: "Rivers / Lakes / Ghats" }
  ],
  "Katihar": [
    { name: "Gorakhnath Temple", category: "Religious" },
    { name: "Gogabil Bird Sanctuary", category: "Wildlife / Nature" },
    { name: "Ramaoatar Park", category: "Parks / Gardens" },
    { name: "Bagi Math", category: "Religious" },
    { name: "Katihar Railway Station Building", category: "Historical" },
    { name: "Mahananda River Ghat", category: "Rivers / Lakes / Ghats" },
    { name: "Balrampur", category: "Cultural / Art villages" },
    { name: "Gandhi Ghar Katihar", category: "Museum / Cultural" },
    { name: "Manihari", category: "Rivers / Lakes / Ghats" },
    { name: "Ahmedabad Fort", category: "Historical" }
  ],
  "Araria": [
    { name: "Kali Mandir Araria", category: "Religious" },
    { name: "Kosi River Bank Araria", category: "Rivers / Lakes / Ghats" },
    { name: "Bhansia", category: "Historical" },
    { name: "Madanpur", category: "Historical" },
    { name: "Bansidhar Temple", category: "Religious" },
    { name: "Forbesganj", category: "Cultural / Art villages" },
    { name: "Renuka Nath Temple", category: "Religious" },
    { name: "Raniganj", category: "Historical" },
    { name: "Zero Mile Araria", category: "Scenic / Viewpoints" },
    { name: "Araria College Campus", category: "Museum / Cultural" }
  ],
  "Kishanganj": [
    { name: "Kishanganj Fort Ruins", category: "Historical" },
    { name: "Nehru Shanti Park", category: "Parks / Gardens" },
    { name: "Mahananda River Bank", category: "Rivers / Lakes / Ghats" },
    { name: "Thakurganj", category: "Historical" },
    { name: "Kachuadah Lake", category: "Rivers / Lakes / Ghats" },
    { name: "Jama Masjid Kishanganj", category: "Religious" },
    { name: "Kali Temple Kishanganj", category: "Religious" },
    { name: "Tea Gardens of Kishanganj", category: "Scenic / Viewpoints" },
    { name: "Kargali", category: "Cultural / Art villages" },
    { name: "Pothia", category: "Rivers / Lakes / Ghats" }
  ],
  "Banka": [
    { name: "Mandar Hill Banka", category: "Hills / Caves" },
    { name: "Chandan Dam", category: "Rivers / Lakes / Ghats" },
    { name: "Jethian", category: "Historical" },
    { name: "Bausi Mela", category: "Cultural / Art villages" },
    { name: "Narsingh Avtar Temple", category: "Religious" },
    { name: "Papaharni Sarovar", category: "Rivers / Lakes / Ghats" },
    { name: "Odhani Dam", category: "Rivers / Lakes / Ghats" },
    { name: "Amba Reservoir", category: "Rivers / Lakes / Ghats" },
    { name: "Bhaljor", category: "Historical" },
    { name: "Laxmipur Tower", category: "Historical" }
  ],
  "Jamui": [
    { name: "Jain Mandir Lachhuar", category: "Religious" },
    { name: "Kshatriya Kund", category: "Historical" },
    { name: "Giddheshwar Temple", category: "Religious" },
    { name: "Simultala Hill Station", category: "Hills / Caves" },
    { name: "Minto Tower", category: "Historical" },
    { name: "Pataneshwar Mandir", category: "Religious" },
    { name: "Nagi Dam Bird Sanctuary", category: "Wildlife / Nature" },
    { name: "Nakti Dam Bird Sanctuary", category: "Wildlife / Nature" },
    { name: "Kumar Gram", category: "Historical" },
    { name: "Kali Mandir Jamui", category: "Religious" }
  ],
  "Lakhisarai": [
    { name: "Ashokdham Temple", category: "Religious" },
    { name: "Jalappa Asthan", category: "Religious" },
    { name: "Shrungi Rishi", category: "Religious" },
    { name: "Munger Surya Mandir Phase", category: "Religious" },
    { name: "Kiul Bridge", category: "Historical" },
    { name: "Abhaipur", category: "Historical" },
    { name: "Surajgarha", category: "Historical" },
    { name: "Nongarh", category: "Historical" },
    { name: "Barahiya", category: "Cultural / Art villages" },
    { name: "Lakhisarai Museum", category: "Museum / Cultural" }
  ],
  "Sheikhpura": [
    { name: "Girihinda Mountain", category: "Hills / Caves" },
    { name: "Sheikhpura Khandaha", category: "Historical" },
    { name: "Mahadev Sthan", category: "Religious" },
    { name: "Kusumha", category: "Rivers / Lakes / Ghats" },
    { name: "Ghoswari", category: "Historical" },
    { name: "Chewara", category: "Cultural / Art villages" },
    { name: "Sheikhpura Dargah", category: "Religious" },
    { name: "Ariari", category: "Historical" },
    { name: "Tripurari Temple", category: "Religious" },
    { name: "Purani Bazar Sheikhpura", category: "Historical" }
  ],
  "Begusarai": [
    { name: "Kanwar Lake Bird Sanctuary", category: "Wildlife / Nature" },
    { name: "Naulakha Temple", category: "Religious" },
    { name: "Simaria River Ghat", category: "Rivers / Lakes / Ghats" },
    { name: "Jai Mangla Temple", category: "Religious" },
    { name: "Hari Giri Dham", category: "Religious" },
    { name: "Begusarai Museum", category: "Museum / Cultural" },
    { name: "Radha Krishna Temple", category: "Religious" },
    { name: "Rajnendra Setu", category: "Historical" },
    { name: "Bakhri", category: "Historical" },
    { name: "Garhpura", category: "Historical" }
  ],
  "Khagaria": [
    { name: "Katyayani Sthan", category: "Religious" },
    { name: "Gogri Jamaalpur", category: "Historical" },
    { name: "Mansinghi Mela", category: "Cultural / Art villages" },
    { name: "Sikarhatti", category: "Rivers / Lakes / Ghats" },
    { name: "Sonbarsa Raj", category: "Historical" },
    { name: "Khagaria Ghats", category: "Rivers / Lakes / Ghats" },
    { name: "Chauti Asthan", category: "Religious" },
    { name: "Alauli", category: "Historical" },
    { name: "Bela", category: "Cultural / Art villages" },
    { name: "Parbatta", category: "Historical" }
  ]
};
